<?php

namespace Relaxstyle\IndexBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FindlistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FindlistRepository extends EntityRepository
{
}
